#pragma once
#include "Screen.h"
#include "Loader.h"
#include <SFML\Graphics.hpp>
#include <SFML\Audio.hpp>
#include "Bullet.h"
#include "Player.h"
#include <iostream>
#include <math.h>
#include <vector>
#include "Enemy.h"
#include "Marauder.h"
#include "Drone.h"
#include "GameState.h"
#include "Logics.h"
#include "Powerups.h"
#include "Loader.h"
#include "Screen.h"
#include "Explosion.h"
#include "Missile.h"
#include <stdlib.h>